# 網站配置
# 主題名稱，對應至目錄：./theme/xxxx
theme: default

# HTML 語言設定
lang: "zh-TW"

# 插件（目前無特殊數字抓取需求，留空即可）
plugins:

# Google Analytics 追蹤 ID (若未來有申請可填入)
google_analytics_id:

# HTML 標題
title: "橙色的品源"

# 頭像圖片路徑 (請記得將您的專屬 Logo 圖片存成 profile.jpeg 放入 images 資料夾替換)
avatar: "./images/profile.jpg"

# 名稱區塊文字
name: "橙色的品源"

# 標語區塊文字 (使用 |- 來保留您設計的換行排版)
tagline: |-
  用影像記錄土地信仰，捕捉台灣文化與人文脈動。
  <br>橙色的品源帶你走訪台灣!
  <br>🎥 台灣宗教民俗文化記錄頻道
  <br>    這裡專注於紀錄台灣的宗教信仰、廟會活動、民俗文化與傳統習俗。
  <br>    偶爾也會分享旅遊景點、環島健行、在地美食與生活日常。
  <br>👉 歡迎訂閱下面各平台，帶你一起認識台灣!
  <br>Capturing the heart of Taiwan’s traditions through my lens.
  <br>Hey, I’m Pinyuan! Join me as I explore the hidden gems of Taiwan.
  <br>🎥 Documenting Taiwan’s Religious & Folk Culture
  <br>This channel is all about Taiwan’s spiritual life—from vibrant temple fairs and ancient folk rituals to the traditions that define us.
  <br>You’ll also find me sharing my travel adventures, hiking trips, local eats, and everyday life.
  <br>👉 Subscribe and follow my journey to discover the real Taiwan!
# 連結列表
links:
  - link:
      icon: "fa-brands fa-youtube"
      text: "Youtube>影片在這"
      url: "https://www.youtube.com/@yake2434"
      alt: "橙色的品源 Youtube 頻道"
      title: "橙色的品源 Youtube 頻道"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram>相片在這"
      url: "https://www.instagram.com/yake2434"
      alt: "橙色的品源 Instagram"
      title: "橙色的品源 Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-facebook"
      text: "Facebook>相簿在這"
      url: "https://facebook.com/yake2434"
      alt: "橙色的品源 Facebook"
      title: "橙色的品源 Facebook"
      target: "_blank"
socials:  
- social:  
      icon: "fa-solid fa-envelope"  
      url: "yake2434@gmail.com"  
      title: "Email: yake2434@gmail.com"  
      alt: "yake2434@gmail.com"  
      target: "_blank"  
# 頁尾文字
footer: >
  歡迎邀請拍攝！相關合作請私訊 Instagram 或 Facebook 或mail到 yake2434@gmail.com 與我聯繫。

# 頁尾版權聲明
copyright: >
  © 2026 橙色的品源。由 <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a> 提供技術支持。
